f=open("demofile.txt","w")
f.write("Hello , World!\n")
f.write("Welcome to Python File Handling.")
f.close()
x=open("demofile.txt" , "r")
print(x.readline())
y=open("demofile.txt" , "a")
y.write("\nThis is an additional line.")
y.close()
print(x.read())
